volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_static:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend:
    container_name: foodgram-backend
    image: satoshiin/foodgram_backend
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    container_name: foodgram-front
    image: satoshiin/foodgram_frontend
    volumes:
      - frontend_static:/app/frontend_build/

  # nginx:
  #   container_name: foodgram-proxy
  #   image: nginx:1.25.4-alpine
  #   ports:
  #     - "8888:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf 
  #     - static_volume:/app/static/
  #     - media_volume:/app/media/
  #   depends_on:
  #     - backend
